//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Tool.Import.App_Code.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__DepotOrderFlow
    {
        public int AppD_ID { get; set; }
        public string MainID { get; set; }
        public string 步骤 { get; set; }
        public string 办理人 { get; set; }
        public string 状态 { get; set; }
        public string 意见 { get; set; }
        public string 时间 { get; set; }
    }
}
