//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Tool.Import.App_Code.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.DepartmentChildren = new HashSet<Department>();
            this.DepartmentAll = new HashSet<Department>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public System.Guid TopId { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public int Level { get; set; }
        public bool Hidden { get; set; }
        public int Type { get; set; }
        public State State { get; set; }
        public int Ordinal { get; set; }
        public int AutoId { get; set; }
        public int BuildType { get; set; }
        public int ClassType { get; set; }
        public string Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> DepartmentChildren { get; set; }
        public virtual Department DepartmentParent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> DepartmentAll { get; set; }
        public virtual Department DepartmentCampus { get; set; }
    }
}
