//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Tool.Import.App_Code.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepotIn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DepotIn()
        {
            this.DepotInX = new HashSet<DepotInX>();
            this.DepotRedo = new HashSet<DepotRedo>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid OrderId { get; set; }
        public System.Guid ObjectId { get; set; }
        public string Age { get; set; }
        public string Place { get; set; }
        public Nullable<System.Guid> ResponsibleId { get; set; }
        public string Note { get; set; }
        public System.DateTime Time { get; set; }
        public System.Guid OperatorId { get; set; }
        public System.DateTime OperationTime { get; set; }
        public decimal Amount { get; set; }
        public decimal PriceSet { get; set; }
        public decimal Price { get; set; }
        public decimal Total { get; set; }
        public decimal AvailableAmount { get; set; }
    
        public virtual DepotObject DepotObject { get; set; }
        public virtual DepotOrder DepotOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepotInX> DepotInX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepotRedo> DepotRedo { get; set; }
    }
}
