//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Tool.Import.App_Code.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepotObjectX
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string PinYin { get; set; }
        public bool Single { get; set; }
        public bool Consumable { get; set; }
        public bool Fixed { get; set; }
        public string Unit { get; set; }
        public string Specification { get; set; }
        public decimal Low { get; set; }
        public decimal High { get; set; }
        public string ImageA { get; set; }
        public string ImageB { get; set; }
        public string ImageC { get; set; }
        public string ImageD { get; set; }
        public string Note { get; set; }
        public int Ordinal { get; set; }
        public int State { get; set; }
        public int AutoId { get; set; }
        public string Code { get; set; }
        public decimal Amount { get; set; }
        public decimal Money { get; set; }
        public Nullable<System.Guid> DepotId { get; set; }
        public string DepotName { get; set; }
        public string FixedCard { get; set; }
        public string FixedNumber { get; set; }
        public string Brand { get; set; }
        public string Extension { get; set; }
        public string Age { get; set; }
    }
}
