//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Tool.Import.App_Code.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepotPeriod
    {
        public System.Guid CatalogId { get; set; }
        public System.Guid DepotId { get; set; }
        public string Users { get; set; }
        public int Time { get; set; }
    
        public virtual DepotCatalog DepotCatalog { get; set; }
    }
}
