//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Tool.Import.App_Code.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepotUseX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DepotUseX()
        {
            this.DepotReturn = new HashSet<DepotReturn>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ObjectId { get; set; }
        public System.Guid UseId { get; set; }
        public System.Guid InXId { get; set; }
        public UseType Type { get; set; }
        public string Age { get; set; }
        public string Place { get; set; }
        public decimal Amount { get; set; }
        public decimal Money { get; set; }
        public decimal ReturnedAmount { get; set; }
        public string Note { get; set; }
    
        public virtual DepotInX DepotInX { get; set; }
        public virtual DepotObject DepotObject { get; set; }
        public virtual DepotUse DepotUse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepotReturn> DepotReturn { get; set; }
    }
}
