//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Tool.Import.App_Code.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepotMember
    {
        public System.Guid Id { get; set; }
        public string RealName { get; set; }
        public string PinYin { get; set; }
        public string Rights { get; set; }
        public System.Guid DepotId { get; set; }
        public System.Guid RoleId { get; set; }
    }
}
