//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Tool.Import.App_Code.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepotUse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DepotUse()
        {
            this.DepotUseX = new HashSet<DepotUseX>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid DepotId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime Time { get; set; }
        public System.Guid OperatorId { get; set; }
        public System.DateTime OperationTime { get; set; }
        public string Age { get; set; }
        public string Place { get; set; }
        public decimal Money { get; set; }
    
        public virtual Depot Depot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepotUseX> DepotUseX { get; set; }
    }
}
