//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Picture.Import.App_Code.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__DepotOrderContent
    {
        public int Id { get; set; }
        public string MainID { get; set; }
        public string 物品名称 { get; set; }
        public string 规格 { get; set; }
        public Nullable<int> 请购数量 { get; set; }
        public string 单价 { get; set; }
        public string 要求 { get; set; }
        public string 用途 { get; set; }
    }
}
