//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Picture.Import.App_Code.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepotObjectSingle
    {
        public System.Guid 仓库Id { get; set; }
        public System.Guid 分类Id { get; set; }
        public System.Guid 物资Id { get; set; }
        public System.DateTime 购置日期 { get; set; }
        public string 仓库 { get; set; }
        public bool 虚拟库 { get; set; }
        public string 物资 { get; set; }
        public string 拼音 { get; set; }
        public string 单位 { get; set; }
        public string 品牌 { get; set; }
        public string 规格 { get; set; }
        public string 适用年龄段 { get; set; }
        public string 条码 { get; set; }
        public decimal 单价 { get; set; }
        public string 卡片编号 { get; set; }
        public string 存放地 { get; set; }
        public string 分类 { get; set; }
    }
}
