//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Picture.Import.App_Code.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepotOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DepotOrder()
        {
            this.DepotIn = new HashSet<DepotIn>();
            this.DepotInX = new HashSet<DepotInX>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid DepotId { get; set; }
        public string Name { get; set; }
        public string Receipt { get; set; }
        public string OrderSource { get; set; }
        public string UsageTarget { get; set; }
        public string Note { get; set; }
        public decimal ToPay { get; set; }
        public decimal Paid { get; set; }
        public Nullable<System.Guid> BrokerageId { get; set; }
        public Nullable<System.Guid> KeeperId { get; set; }
        public bool Done { get; set; }
        public System.DateTime OrderTime { get; set; }
        public System.DateTime RecordTime { get; set; }
        public System.Guid OperatorId { get; set; }
        public System.DateTime OperationTime { get; set; }
        public State State { get; set; }
        public string MainID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepotIn> DepotIn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepotInX> DepotInX { get; set; }
    }
}
