//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Picture.Import.App_Code.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepotUseXRecord
    {
        public System.Guid Id { get; set; }
        public System.Guid CatalogId { get; set; }
        public int Level { get; set; }
        public bool IsVirtual { get; set; }
        public System.Guid UseId { get; set; }
        public System.Guid InXId { get; set; }
        public System.DateTime Time { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public decimal Amount { get; set; }
        public decimal PriceSet { get; set; }
        public decimal Money { get; set; }
        public string Age { get; set; }
        public string UserName { get; set; }
        public string OperatorName { get; set; }
        public string Note { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid OperatorId { get; set; }
        public decimal ReturnedAmount { get; set; }
        public System.Guid ObjectId { get; set; }
        public string CatalogName { get; set; }
        public Nullable<int> Period { get; set; }
    }
}
