//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public string Home { get; set; }
        public string Quit { get; set; }
        public int Type { get; set; }
        public int State { get; set; }
        public int Ordinal { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Children = new HashSet<Department>();
            this.CampusChildren = new HashSet<Department>();
            this.Users = new HashSet<DepartmentUser>();
            this.CampusUsers = new HashSet<DepartmentUser>();
            this.Storage = new HashSet<Storage>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public System.Guid TopId { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public int Level { get; set; }
        public bool Hidden { get; set; }
        public int Type { get; set; }
        public State State { get; set; }
        public int Ordinal { get; set; }
        public int AutoId { get; set; }
        public int BuildType { get; set; }
        public int ClassType { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Department> Children { get; set; }
        public virtual Department Parent { get; set; }
        public virtual ICollection<Department> CampusChildren { get; set; }
        public virtual Department Campus { get; set; }
        public virtual ICollection<DepartmentUser> Users { get; set; }
        public virtual ICollection<DepartmentUser> CampusUsers { get; set; }
        public virtual ICollection<Storage> Storage { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentUser
    {
        public System.Guid DepartmentId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid TopDepartmentId { get; set; }
        public DepartmentUserType Type { get; set; }
        public System.DateTime Time { get; set; }
        public State State { get; set; }
        public int Ordinal { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Department Campus { get; set; }
        public virtual User User { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public Storage()
        {
            this.StorageCatalog = new HashSet<StorageCatalog>();
            this.StorageFlow = new HashSet<StorageFlow>();
            this.StorageTarget = new HashSet<StorageTarget>();
            this.StorageDictionary = new HashSet<StorageDictionary>();
            this.StorageObject = new HashSet<StorageObject>();
            this.StorageRole = new HashSet<StorageRole>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid CampusId { get; set; }
        public int Ordinal { get; set; }
        public State State { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<StorageCatalog> StorageCatalog { get; set; }
        public virtual ICollection<StorageFlow> StorageFlow { get; set; }
        public virtual ICollection<StorageTarget> StorageTarget { get; set; }
        public virtual ICollection<StorageDictionary> StorageDictionary { get; set; }
        public virtual ICollection<StorageObject> StorageObject { get; set; }
        public virtual ICollection<StorageRole> StorageRole { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageCatalog
    {
        public StorageCatalog()
        {
            this.Children = new HashSet<StorageCatalog>();
            this.StorageFlow = new HashSet<StorageFlow>();
            this.StorageObject = new HashSet<StorageObject>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public System.Guid StorageId { get; set; }
        public string Name { get; set; }
        public int Ordinal { get; set; }
        public State State { get; set; }
        public string PinYin { get; set; }
        public int AutoId { get; set; }
        public string Code { get; set; }
    
        public virtual Storage Storage { get; set; }
        public virtual ICollection<StorageCatalog> Children { get; set; }
        public virtual StorageCatalog Parent { get; set; }
        public virtual ICollection<StorageFlow> StorageFlow { get; set; }
        public virtual ICollection<StorageObject> StorageObject { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageConsume
    {
        public StorageConsume()
        {
            this.StorageConsumeSingle = new HashSet<StorageConsumeSingle>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ObjectId { get; set; }
        public Nullable<System.Guid> ConsumeUserId { get; set; }
        public System.Guid OperationUserId { get; set; }
        public int TimeNode { get; set; }
        public System.DateTime Time { get; set; }
        public int Amount { get; set; }
        public decimal PerPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal AdditionalFee { get; set; }
        public decimal TotalMoney { get; set; }
        public string Note { get; set; }
    
        public virtual User ConsumeUser { get; set; }
        public virtual User Operator { get; set; }
        public virtual ICollection<StorageConsumeSingle> StorageConsumeSingle { get; set; }
        public virtual StorageObject StorageObject { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageConsumeSingle
    {
        public System.Guid Id { get; set; }
        public System.Guid ConsumeId { get; set; }
        public System.Guid InId { get; set; }
        public int ConsumeOrdinal { get; set; }
        public int OriginalAmount { get; set; }
        public int ConsumedAmount { get; set; }
    
        public virtual StorageConsume StorageConsume { get; set; }
        public virtual StorageIn StorageIn { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageDictionary
    {
        public string Name { get; set; }
        public DictionaryType Type { get; set; }
        public System.Guid StorageId { get; set; }
        public string PinYin { get; set; }
    
        public virtual Storage Storage { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageFlow
    {
        public System.Guid Id { get; set; }
        public System.Guid StorageId { get; set; }
        public System.Guid CatalogId { get; set; }
        public System.Guid ObjectId { get; set; }
        public FlowType Type { get; set; }
        public int TimeNode { get; set; }
        public System.DateTime Time { get; set; }
        public int Amount { get; set; }
        public decimal PerPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal AdditionalFee { get; set; }
        public System.Guid RelativeId { get; set; }
        public System.Guid RelativeSingleId { get; set; }
        public int InitialInAmount { get; set; }
        public decimal InitialInMoney { get; set; }
        public int InitialLendAmount { get; set; }
        public decimal InitialLendMoney { get; set; }
        public int InitialTotalAmount { get; set; }
        public decimal InitialTotalMoney { get; set; }
        public int FinalInAmount { get; set; }
        public decimal FinalInMoney { get; set; }
        public int FinalLendAmount { get; set; }
        public decimal FinalLendMoney { get; set; }
        public int FinalTotalAmount { get; set; }
        public decimal FinalTotalMoney { get; set; }
        public string Note { get; set; }
        public int InitialOutAmount { get; set; }
        public decimal InitialOutMoney { get; set; }
        public int FinalOutAmount { get; set; }
        public decimal FinalOutMoney { get; set; }
    
        public virtual Storage Storage { get; set; }
        public virtual StorageCatalog StorageCatalog { get; set; }
        public virtual StorageObject StorageObject { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageIn
    {
        public StorageIn()
        {
            this.StorageConsumeSingle = new HashSet<StorageConsumeSingle>();
            this.StorageInSingle = new HashSet<StorageInSingle>();
            this.StorageLendSingle = new HashSet<StorageLendSingle>();
            this.StorageOutSingle = new HashSet<StorageOutSingle>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ObjectId { get; set; }
        public System.Guid TargetId { get; set; }
        public string Age { get; set; }
        public string Place { get; set; }
        public string Image { get; set; }
        public Nullable<System.Guid> ResponsibleUserId { get; set; }
        public System.Guid OperationUserId { get; set; }
        public int TimeNode { get; set; }
        public System.DateTime Time { get; set; }
        public int Amount { get; set; }
        public decimal PerPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal AdditionalFee { get; set; }
        public int InAmount { get; set; }
        public decimal InMoney { get; set; }
        public int LendAmount { get; set; }
        public decimal LendMoney { get; set; }
        public int OutAmount { get; set; }
        public decimal OutMoney { get; set; }
        public int TotalAmount { get; set; }
        public decimal TotalMoney { get; set; }
        public string Note { get; set; }
        public int AutoId { get; set; }
    
        public virtual ICollection<StorageConsumeSingle> StorageConsumeSingle { get; set; }
        public virtual User ResponsibleUser { get; set; }
        public virtual User Operator { get; set; }
        public virtual ICollection<StorageInSingle> StorageInSingle { get; set; }
        public virtual ICollection<StorageLendSingle> StorageLendSingle { get; set; }
        public virtual ICollection<StorageOutSingle> StorageOutSingle { get; set; }
        public virtual StorageTarget StorageTarget { get; set; }
        public virtual StorageObject StorageObject { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageInSingle
    {
        public System.Guid Id { get; set; }
        public System.Guid InId { get; set; }
        public int InOrdinal { get; set; }
        public bool In { get; set; }
        public bool Lend { get; set; }
        public bool Out { get; set; }
        public System.Guid ObjectId { get; set; }
        public int AutoId { get; set; }
        public string Place { get; set; }
    
        public virtual StorageIn StorageIn { get; set; }
        public virtual StorageObject StorageObject { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageLend
    {
        public StorageLend()
        {
            this.StorageLendSingle = new HashSet<StorageLendSingle>();
            this.StorageReturnSingle = new HashSet<StorageReturnSingle>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ObjectId { get; set; }
        public Nullable<System.Guid> BorrowUserId { get; set; }
        public System.Guid OperationUserId { get; set; }
        public int TimeNode { get; set; }
        public System.DateTime Time { get; set; }
        public int Amount { get; set; }
        public decimal PerPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal AdditionalFee { get; set; }
        public decimal TotalMoney { get; set; }
        public string Note { get; set; }
        public int ReturnedAmount { get; set; }
        public bool Returned { get; set; }
    
        public virtual User BorrowUser { get; set; }
        public virtual User Operator { get; set; }
        public virtual ICollection<StorageLendSingle> StorageLendSingle { get; set; }
        public virtual ICollection<StorageReturnSingle> StorageReturnSingle { get; set; }
        public virtual StorageObject StorageObject { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageLendSingle
    {
        public System.Guid Id { get; set; }
        public System.Guid LendId { get; set; }
        public System.Guid InId { get; set; }
        public int LendAmount { get; set; }
        public int Ordinal { get; set; }
        public bool Returned { get; set; }
        public int ReturnedAmount { get; set; }
    
        public virtual StorageIn StorageIn { get; set; }
        public virtual StorageLend StorageLend { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageObject
    {
        public StorageObject()
        {
            this.StorageConsume = new HashSet<StorageConsume>();
            this.StorageFlow = new HashSet<StorageFlow>();
            this.StorageIn = new HashSet<StorageIn>();
            this.StorageLend = new HashSet<StorageLend>();
            this.StorageOut = new HashSet<StorageOut>();
            this.StorageReturn = new HashSet<StorageReturn>();
            this.StorageInSingle = new HashSet<StorageInSingle>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid StorageId { get; set; }
        public System.Guid CatalogId { get; set; }
        public string Name { get; set; }
        public string PinYin { get; set; }
        public string Unit { get; set; }
        public string Specification { get; set; }
        public bool Single { get; set; }
        public bool Consumable { get; set; }
        public bool Fixed { get; set; }
        public string FixedSerial { get; set; }
        public int Low { get; set; }
        public int High { get; set; }
        public string Image { get; set; }
        public System.Guid OperationUserId { get; set; }
        public int Ordinal { get; set; }
        public State State { get; set; }
        public int TimeNode { get; set; }
        public System.DateTime Time { get; set; }
        public int InAmount { get; set; }
        public decimal InMoney { get; set; }
        public int LendAmount { get; set; }
        public decimal LendMoney { get; set; }
        public int OutAmount { get; set; }
        public decimal OutMoney { get; set; }
        public int TotalAmount { get; set; }
        public decimal TotalMoney { get; set; }
        public System.Guid LastFlowId { get; set; }
        public string Note { get; set; }
        public int AutoId { get; set; }
        public string Code { get; set; }
    
        public virtual Storage Storage { get; set; }
        public virtual StorageCatalog StorageCatalog { get; set; }
        public virtual ICollection<StorageConsume> StorageConsume { get; set; }
        public virtual ICollection<StorageFlow> StorageFlow { get; set; }
        public virtual ICollection<StorageIn> StorageIn { get; set; }
        public virtual ICollection<StorageLend> StorageLend { get; set; }
        public virtual ICollection<StorageOut> StorageOut { get; set; }
        public virtual ICollection<StorageReturn> StorageReturn { get; set; }
        public virtual ICollection<StorageInSingle> StorageInSingle { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageOut
    {
        public StorageOut()
        {
            this.StorageOutSingle = new HashSet<StorageOutSingle>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ObjectId { get; set; }
        public Nullable<System.Guid> OutUserId { get; set; }
        public System.Guid OperationUserId { get; set; }
        public OutType Type { get; set; }
        public string Reason { get; set; }
        public int TimeNode { get; set; }
        public System.DateTime Time { get; set; }
        public int Amount { get; set; }
        public decimal PerPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal AdditionalFee { get; set; }
        public decimal TotalMoney { get; set; }
        public string Note { get; set; }
    
        public virtual User OutUser { get; set; }
        public virtual User Operator { get; set; }
        public virtual ICollection<StorageOutSingle> StorageOutSingle { get; set; }
        public virtual StorageObject StorageObject { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageOutSingle
    {
        public System.Guid Id { get; set; }
        public System.Guid OutId { get; set; }
        public System.Guid InId { get; set; }
        public int OriginalAmount { get; set; }
        public int OutAmount { get; set; }
        public int Ordinal { get; set; }
    
        public virtual StorageIn StorageIn { get; set; }
        public virtual StorageOut StorageOut { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoragePlace
    {
        public System.Guid Id { get; set; }
        public bool IsSingle { get; set; }
        public System.Guid InId { get; set; }
        public string Place { get; set; }
        public int TimeNode { get; set; }
        public System.DateTime Time { get; set; }
        public System.Guid UserId { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageQueryObject
    {
        public System.Guid Id { get; set; }
        public string 名称 { get; set; }
        public string PinYin { get; set; }
        public int 库存量 { get; set; }
        public decimal 库存金额 { get; set; }
        public int 总量 { get; set; }
        public decimal 总金额 { get; set; }
        public string 单位 { get; set; }
        public string 规格 { get; set; }
        public bool Single { get; set; }
        public bool Consumable { get; set; }
        public bool Fixed { get; set; }
        public int Low { get; set; }
        public int High { get; set; }
        public System.Guid CatalogId { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageReturn
    {
        public StorageReturn()
        {
            this.StorageReturnSingle = new HashSet<StorageReturnSingle>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ObjectId { get; set; }
        public Nullable<System.Guid> ReturnUserId { get; set; }
        public System.Guid OperationUserId { get; set; }
        public int TimeNode { get; set; }
        public System.DateTime Time { get; set; }
        public int Amount { get; set; }
        public decimal PerPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal AdditionalFee { get; set; }
        public decimal TotalMoney { get; set; }
        public string Note { get; set; }
    
        public virtual User ReturnUser { get; set; }
        public virtual User Operator { get; set; }
        public virtual ICollection<StorageReturnSingle> StorageReturnSingle { get; set; }
        public virtual StorageObject StorageObject { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageReturnSingle
    {
        public System.Guid Id { get; set; }
        public System.Guid ReturnId { get; set; }
        public System.Guid LendId { get; set; }
        public int ReturnedAmount { get; set; }
        public int Ordinal { get; set; }
    
        public virtual StorageLend StorageLend { get; set; }
        public virtual StorageReturn StorageReturn { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageRole
    {
        public StorageRole()
        {
            this.StorageRoleRight = new HashSet<StorageRoleRight>();
            this.User = new HashSet<User>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid StorageId { get; set; }
        public string Name { get; set; }
        public State State { get; set; }
        public int Ordinal { get; set; }
    
        public virtual Storage Storage { get; set; }
        public virtual ICollection<StorageRoleRight> StorageRoleRight { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageRoleRight
    {
        public System.Guid RoleId { get; set; }
        public string Right { get; set; }
    
        public virtual StorageRole StorageRole { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageTarget
    {
        public StorageTarget()
        {
            this.StorageIn = new HashSet<StorageIn>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid StorageId { get; set; }
        public string ReceiptNumber { get; set; }
        public string OrderSource { get; set; }
        public string UsageTarget { get; set; }
        public string Content { get; set; }
        public decimal ToPay { get; set; }
        public decimal Paid { get; set; }
        public Nullable<System.Guid> BrokerageUserId { get; set; }
        public Nullable<System.Guid> KeepUserId { get; set; }
        public System.Guid OperationUserId { get; set; }
        public bool In { get; set; }
        public int TimeNode { get; set; }
        public System.DateTime Time { get; set; }
        public string Number { get; set; }
    
        public virtual Storage Storage { get; set; }
        public virtual User BrokerageUser { get; set; }
        public virtual User KeepUser { get; set; }
        public virtual User Operator { get; set; }
        public virtual ICollection<StorageIn> StorageIn { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public System.Guid Id { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Birthplace { get; set; }
        public string Address { get; set; }
        public string Nationality { get; set; }
        public string IDCard { get; set; }
        public int AutoId { get; set; }
        public bool PerStaff { get; set; }
        public bool Sync { get; set; }
    
        public virtual User User { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserOnline = new HashSet<UserOnline>();
            this.DepartmentUser = new HashSet<DepartmentUser>();
            this.ConsumUser = new HashSet<StorageConsume>();
            this.ConsumeOperator = new HashSet<StorageConsume>();
            this.ResponsibleUser = new HashSet<StorageIn>();
            this.InOperator = new HashSet<StorageIn>();
            this.BorrowUser = new HashSet<StorageLend>();
            this.LendOperator = new HashSet<StorageLend>();
            this.OutUser = new HashSet<StorageOut>();
            this.OutOperator = new HashSet<StorageOut>();
            this.ReturnUser = new HashSet<StorageReturn>();
            this.ReturnOperator = new HashSet<StorageReturn>();
            this.BrokerageUser = new HashSet<StorageTarget>();
            this.KeepUser = new HashSet<StorageTarget>();
            this.TargetOperator = new HashSet<StorageTarget>();
            this.StorageRole = new HashSet<StorageRole>();
        }
    
        public System.Guid Id { get; set; }
        public string Account { get; set; }
        public string RealName { get; set; }
        public string DisplayName { get; set; }
        public string Icon { get; set; }
        public System.Guid Stamp { get; set; }
        public string Password { get; set; }
        public string PasswordEx { get; set; }
        public string CryptoKey { get; set; }
        public string CryptoSalt { get; set; }
        public int Type { get; set; }
        public State State { get; set; }
        public int Ordinal { get; set; }
        public string Description { get; set; }
        public string PinYin { get; set; }
    
        public virtual ICollection<UserOnline> UserOnline { get; set; }
        public virtual ICollection<DepartmentUser> DepartmentUser { get; set; }
        public virtual ICollection<StorageConsume> ConsumUser { get; set; }
        public virtual ICollection<StorageConsume> ConsumeOperator { get; set; }
        public virtual ICollection<StorageIn> ResponsibleUser { get; set; }
        public virtual ICollection<StorageIn> InOperator { get; set; }
        public virtual ICollection<StorageLend> BorrowUser { get; set; }
        public virtual ICollection<StorageLend> LendOperator { get; set; }
        public virtual ICollection<StorageOut> OutUser { get; set; }
        public virtual ICollection<StorageOut> OutOperator { get; set; }
        public virtual ICollection<StorageReturn> ReturnUser { get; set; }
        public virtual ICollection<StorageReturn> ReturnOperator { get; set; }
        public virtual ICollection<StorageTarget> BrokerageUser { get; set; }
        public virtual ICollection<StorageTarget> KeepUser { get; set; }
        public virtual ICollection<StorageTarget> TargetOperator { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<StorageRole> StorageRole { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOnline
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual User User { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTeacher
    {
        public System.Guid Id { get; set; }
        public string Account { get; set; }
        public string RealName { get; set; }
        public string DisplayName { get; set; }
        public string PinYin { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Birthplace { get; set; }
        public string Address { get; set; }
        public string Nationality { get; set; }
        public string IDCard { get; set; }
        public bool PerStaff { get; set; }
        public bool Sync { get; set; }
        public int AutoId { get; set; }
        public int PriorOrdinal { get; set; }
        public System.Guid DepartmentId { get; set; }
        public Nullable<System.Guid> TopDepartmentId { get; set; }
        public State State { get; set; }
        public string DepartmentName { get; set; }
        public string DeaprtmentDisplayName { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> MinorOrdinal { get; set; }
        public DepartmentUserType Type { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 查询_报废单
    {
        public System.Guid 报废标识 { get; set; }
        public System.Guid 物品标识 { get; set; }
        public System.Guid 报废人标识 { get; set; }
        public string 报废人 { get; set; }
        public System.Guid 操作人标识 { get; set; }
        public string 操作人 { get; set; }
        public string 报废原因 { get; set; }
        public string 报废类型 { get; set; }
        public int 日期 { get; set; }
        public System.DateTime 时间 { get; set; }
        public int 数量 { get; set; }
        public decimal 单价 { get; set; }
        public decimal 总价 { get; set; }
        public decimal 优惠价 { get; set; }
        public decimal 合计 { get; set; }
        public string 备注 { get; set; }
        public System.Guid 分类标识 { get; set; }
        public string 物品名称 { get; set; }
        public string 单位 { get; set; }
        public string 规格 { get; set; }
        public string 拼音 { get; set; }
        public bool 易耗品 { get; set; }
        public bool 固定资产 { get; set; }
        public string 固定资产编号 { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 查询_购置单
    {
        public System.Guid 主键 { get; set; }
        public System.Guid 仓库 { get; set; }
        public string 购置单号 { get; set; }
        public string 发票编号 { get; set; }
        public string 采购来源 { get; set; }
        public string 使用对象 { get; set; }
        public string 清单简述 { get; set; }
        public decimal 应付金额 { get; set; }
        public decimal 实付金额 { get; set; }
        public string 经手人 { get; set; }
        public string 保管人 { get; set; }
        public bool 是否入库 { get; set; }
        public int 采购日期 { get; set; }
        public string 操作人 { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 查询_归还单
    {
        public System.Guid 归还标识 { get; set; }
        public System.Guid 物品标识 { get; set; }
        public System.Guid 归还人标识 { get; set; }
        public string 归还人 { get; set; }
        public System.Guid 操作人标识 { get; set; }
        public string 操作人 { get; set; }
        public int 日期 { get; set; }
        public System.DateTime 时间 { get; set; }
        public int 数量 { get; set; }
        public decimal 单价 { get; set; }
        public decimal 总价 { get; set; }
        public decimal 优惠价 { get; set; }
        public decimal 合计 { get; set; }
        public string 备注 { get; set; }
        public System.Guid 分类标识 { get; set; }
        public string 物品名称 { get; set; }
        public string 单位 { get; set; }
        public string 规格 { get; set; }
        public string 拼音 { get; set; }
        public bool 易耗品 { get; set; }
        public bool 固定资产 { get; set; }
        public string 固定资产编号 { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 查询_借还流
    {
        public System.Guid 单借标识 { get; set; }
        public int 编号 { get; set; }
        public System.Guid 借标识 { get; set; }
        public System.Guid 物品标识 { get; set; }
        public Nullable<System.Guid> 人员标识 { get; set; }
        public int 时间节点 { get; set; }
        public System.DateTime 时间 { get; set; }
        public System.Guid 单入标识 { get; set; }
        public int TotalAmount { get; set; }
        public decimal TotalMoney { get; set; }
        public System.Guid 仓库标识 { get; set; }
        public string 仓库名称 { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 查询_借用单
    {
        public System.Guid 借用标识 { get; set; }
        public System.Guid 物品标识 { get; set; }
        public System.Guid 借用人标识 { get; set; }
        public string 借用人 { get; set; }
        public System.Guid 操作人标识 { get; set; }
        public string 操作人 { get; set; }
        public int 日期 { get; set; }
        public System.DateTime 时间 { get; set; }
        public int 数量 { get; set; }
        public decimal 单价 { get; set; }
        public decimal 总价 { get; set; }
        public decimal 优惠价 { get; set; }
        public decimal 合计 { get; set; }
        public string 备注 { get; set; }
        public System.Guid 分类标识 { get; set; }
        public string 物品名称 { get; set; }
        public string 单位 { get; set; }
        public string 规格 { get; set; }
        public string 拼音 { get; set; }
        public bool 易耗品 { get; set; }
        public bool 固定资产 { get; set; }
        public string 固定资产编号 { get; set; }
        public bool 是否归还 { get; set; }
        public Nullable<int> 待归还数 { get; set; }
        public System.Guid 仓库标识 { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 查询_领用单
    {
        public System.Guid 领用标识 { get; set; }
        public System.Guid 物品标识 { get; set; }
        public System.Guid 领用人标识 { get; set; }
        public string 领用人 { get; set; }
        public System.Guid 操作人标识 { get; set; }
        public string 操作人 { get; set; }
        public int 日期 { get; set; }
        public System.DateTime 时间 { get; set; }
        public int 数量 { get; set; }
        public decimal 单价 { get; set; }
        public decimal 总价 { get; set; }
        public decimal 优惠价 { get; set; }
        public decimal 合计 { get; set; }
        public string 备注 { get; set; }
        public System.Guid 分类标识 { get; set; }
        public string 物品名称 { get; set; }
        public string 单位 { get; set; }
        public string 规格 { get; set; }
        public string 拼音 { get; set; }
        public bool 易耗品 { get; set; }
        public bool 固定资产 { get; set; }
        public string 固定资产编号 { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 查询_盘库流
    {
        public System.Guid 单计标识 { get; set; }
        public System.Guid 物品标识 { get; set; }
        public System.Guid 入库标识 { get; set; }
        public int 编号 { get; set; }
        public bool 在库 { get; set; }
        public string 存放地 { get; set; }
        public int 二维码标识 { get; set; }
        public string 物品名称 { get; set; }
        public System.Guid 仓库标识 { get; set; }
        public string 固定资产编号 { get; set; }
        public string 入库存放地 { get; set; }
        public Nullable<System.Guid> 人员标识 { get; set; }
        public string 责任人 { get; set; }
        public string 责任人拼音 { get; set; }
        public string 物品拼音 { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 查询_入库单
    {
        public System.Guid 入库标识 { get; set; }
        public System.Guid 物品标识 { get; set; }
        public System.Guid 购置标识 { get; set; }
        public string 年龄段 { get; set; }
        public string 存放地 { get; set; }
        public System.Guid 责任人标识 { get; set; }
        public string 责任人 { get; set; }
        public System.Guid 操作人标识 { get; set; }
        public string 操作人 { get; set; }
        public int 日期 { get; set; }
        public System.DateTime 时间 { get; set; }
        public int 数量 { get; set; }
        public decimal 单价 { get; set; }
        public decimal 总价 { get; set; }
        public decimal 优惠价 { get; set; }
        public decimal 合计 { get; set; }
        public string 备注 { get; set; }
        public System.Guid 分类标识 { get; set; }
        public string 物品名称 { get; set; }
        public string 单位 { get; set; }
        public string 规格 { get; set; }
        public string 拼音 { get; set; }
        public bool 易耗品 { get; set; }
        public bool 固定资产 { get; set; }
        public string 固定资产编号 { get; set; }
        public string 购置单号 { get; set; }
        public string 发票编号 { get; set; }
        public string 采购来源 { get; set; }
        public string 使用对象 { get; set; }
        public int 库存数量 { get; set; }
    }
}
namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 查询_数据流
    {
        public string Name { get; set; }
        public string PinYin { get; set; }
        public System.Guid Id { get; set; }
        public System.Guid StorageId { get; set; }
        public System.Guid CatalogId { get; set; }
        public System.Guid ObjectId { get; set; }
        public int Type { get; set; }
        public int TimeNode { get; set; }
        public System.DateTime Time { get; set; }
        public int Amount { get; set; }
        public decimal PerPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal AdditionalFee { get; set; }
        public System.Guid RelativeId { get; set; }
        public System.Guid RelativeSingleId { get; set; }
        public int InitialInAmount { get; set; }
        public decimal InitialInMoney { get; set; }
        public int InitialLendAmount { get; set; }
        public decimal InitialLendMoney { get; set; }
        public int InitialOutAmount { get; set; }
        public decimal InitialOutMoney { get; set; }
        public int InitialTotalAmount { get; set; }
        public decimal InitialTotalMoney { get; set; }
        public int FinalInAmount { get; set; }
        public decimal FinalInMoney { get; set; }
        public int FinalLendAmount { get; set; }
        public decimal FinalLendMoney { get; set; }
        public int FinalOutAmount { get; set; }
        public decimal FinalOutMoney { get; set; }
        public int FinalTotalAmount { get; set; }
        public decimal FinalTotalMoney { get; set; }
        public string Note { get; set; }
    }
}
namespace Models
{
    using System;
    
    public partial class QueryStorageBorrow_Result
    {
        public System.Guid Id { get; set; }
        public string Account { get; set; }
        public string RealName { get; set; }
        public string DisplayName { get; set; }
        public string Icon { get; set; }
        public System.Guid Stamp { get; set; }
        public string Password { get; set; }
        public string PasswordEx { get; set; }
        public string CryptoKey { get; set; }
        public string CryptoSalt { get; set; }
        public int Type { get; set; }
        public int State { get; set; }
        public int Ordinal { get; set; }
        public string Description { get; set; }
        public string PinYin { get; set; }
    }
}
namespace Models
{
    using System;
    
    public partial class QueryStorageTarget_Result
    {
        public System.Guid Id { get; set; }
        public System.Guid StorageId { get; set; }
        public string Number { get; set; }
        public string ReceiptNumber { get; set; }
        public System.Guid OrderSource { get; set; }
        public System.Guid UsageTarget { get; set; }
        public string Content { get; set; }
        public decimal ToPay { get; set; }
        public decimal Paid { get; set; }
        public Nullable<System.Guid> BrokerageUserId { get; set; }
        public Nullable<System.Guid> KeepUserId { get; set; }
        public System.Guid OperationUserId { get; set; }
        public bool In { get; set; }
        public int TimeNode { get; set; }
        public System.DateTime Time { get; set; }
    }
}
namespace Models
{
    using System;
    
    public enum DepartmentType : int
    {
        学校 = 0,
        部门 = 1
    }
}
namespace Models
{
    using System;
    
    public enum DepartmentUserType : int
    {
        主职 = -1,
        借调 = -4
    }
}
namespace Models
{
    using System;
    
    public enum DictionaryType : int
    {
        单位 = 1,
        规格 = 2,
        采购来源 = 3,
        使用对象 = 4,
        年龄段 = 5,
        存放地 = 6
    }
}
namespace Models
{
    using System;
    
    [Flags]
    public enum FlowType : int
    {
        入库 = 1,
        购置 = 2,
        归还 = 4,
        转入 = 8,
        出库 = 16,
        领用 = 32,
        借用 = 64,
        报废 = 128,
        转出 = 256
    }
}
namespace Models
{
    using System;
    
    public enum OutType : int
    {
        人为损耗 = 1,
        自然损耗 = 2
    }
}
namespace Models
{
    using System;
    
    public enum State : int
    {
        内置 = 0,
        启用 = 1,
        删除 = 5
    }
}
