//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Picture.Import.App_Code.ToModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_picbarcode
    {
        public int pid { get; set; }
        public string txm { get; set; }
        public string opcode { get; set; }
        public Nullable<System.DateTime> opdate { get; set; }
        public string state { get; set; }
    }
}
