//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Picture.Import.App_Code.ToModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_toolimg
    {
        public int tid { get; set; }
        public byte[] pic1 { get; set; }
        public byte[] pic2 { get; set; }
        public byte[] pic3 { get; set; }
        public byte[] pic4 { get; set; }
        public string opcode { get; set; }
        public Nullable<System.DateTime> opdate { get; set; }
    }
}
