//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Picture.Import.App_Code.ToModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibEntities : DbContext
    {
        public LibEntities()
            : base("name=LibEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<P_piccurr> P_piccurr { get; set; }
        public virtual DbSet<P_picinfo> P_picinfo { get; set; }
        public virtual DbSet<P_picimg> P_picimg { get; set; }
        public virtual DbSet<pcodelist> pcodelist { get; set; }
        public virtual DbSet<T_toolinfo> T_toolinfo { get; set; }
        public virtual DbSet<T_toolimg> T_toolimg { get; set; }
    }
}
