//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class Action
    {
        public System.Guid Id { get; set; }
        public ActionType Type { get; set; }
        public System.Guid Id1 { get; set; }
        public System.Guid Id2 { get; set; }
        public Nullable<System.Guid> Id3 { get; set; }
        public Nullable<System.Guid> Id4 { get; set; }
        public string Content1 { get; set; }
        public string Content2 { get; set; }
        public string Content3 { get; set; }
        public string Content4 { get; set; }
        public System.DateTime Time { get; set; }
        public State State { get; set; }
    }
}
