//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    
    public enum ActionType : int
    {
        用户评分资源 = 1,
        用户评论资源 = 2,
        用户收藏资源 = 3,
        用户下载资源 = 4,
        用户访问资源 = 5,
        用户访问用户 = 6,
        用户回复评论 = 7
    }
}
