//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class Api
    {
        public Api()
        {
            this.ApiLog = new HashSet<ApiLog>();
        }
    
        public System.Guid Id { get; set; }
        public string ProviderId { get; set; }
        public System.Guid ProviderKey { get; set; }
        public State State { get; set; }
    
        public virtual ICollection<ApiLog> ApiLog { get; set; }
    }
}
