//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class ApplicationPolicy
    {
        public System.Guid Id { get; set; }
        public System.Guid ApplicationId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public State State { get; set; }
        public string Description { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
