//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class Application
    {
        public Application()
        {
            this.ApplicationPolicy = new HashSet<ApplicationPolicy>();
            this.Menu = new HashSet<Menu>();
            this.Right = new HashSet<Right>();
            this.ApplicationRole = new HashSet<ApplicationRole>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public string Home { get; set; }
        public string Quit { get; set; }
        public ApplicationType Type { get; set; }
        public State State { get; set; }
        public int Ordinal { get; set; }
    
        public virtual ICollection<ApplicationPolicy> ApplicationPolicy { get; set; }
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual ICollection<Right> Right { get; set; }
        public virtual ICollection<ApplicationRole> ApplicationRole { get; set; }
    }
}
