//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class Application
    {
        public Application()
        {
            this.ApplicationPolicy = new HashSet<ApplicationPolicy>();
            this.Menu = new HashSet<Menu>();
            this.Right = new HashSet<Right>();
            this.ApplicationRole = new HashSet<ApplicationRole>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public string Home { get; set; }
        public string Quit { get; set; }
        public ApplicationType Type { get; set; }
        public State State { get; set; }
        public int Ordinal { get; set; }
    
        public virtual ICollection<ApplicationPolicy> ApplicationPolicy { get; set; }
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual ICollection<Right> Right { get; set; }
        public virtual ICollection<ApplicationRole> ApplicationRole { get; set; }
    }
}
