//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class C__机构
    {
        public System.Guid 机构ID { get; set; }
        public string 金和ID { get; set; }
        public string 机构名称 { get; set; }
        public string 机构拼音 { get; set; }
        public Nullable<System.Guid> 父级ID { get; set; }
    }
}
