//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    
    public enum CatalogType : int
    {
        课程 = 2,
        视频 = 3,
        文章 = 4,
        团队_名师 = 5,
        团队_教研 = 6,
        年级_幼儿园 = -1,
        年级_小学 = -2,
        年级_初中 = -3,
        学习小助手 = 1,
        年级_高中 = -4,
        年级_其他 = -5
    }
}
