//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    
    public enum ClassType : int
    {
        九年一贯制 = 1,
        幼儿园 = 2,
        小学 = 3,
        初中 = 4,
        其他 = 5,
        无 = 0,
        高中 = 6
    }
}
