//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class Contact_Users
    {
        public System.Guid CampusId { get; set; }
        public string CampusName { get; set; }
        public System.Guid DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public System.Guid Id { get; set; }
        public string Account { get; set; }
        public string RealName { get; set; }
        public string Icon { get; set; }
        public string WXOpenId { get; set; }
        public string Phone { get; set; }
        public string IDCard { get; set; }
        public bool PerStaff { get; set; }
        public bool Sync { get; set; }
        public int Type { get; set; }
        public int Ordinal { get; set; }
        public string PinYin { get; set; }
    }
}
