//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class Department
    {
        public Department()
        {
            this.DepartmentChildren = new HashSet<Department>();
            this.DepartmentUser = new HashSet<DepartmentUser>();
            this.TopDepartmentUser = new HashSet<DepartmentUser>();
            this.Learned = new HashSet<Learned>();
            this.Taught = new HashSet<Taught>();
            this.Departments = new HashSet<Department>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public System.Guid TopId { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public int Level { get; set; }
        public bool Hidden { get; set; }
        public DepartmentType Type { get; set; }
        public State State { get; set; }
        public int Ordinal { get; set; }
        public BuildType BuildType { get; set; }
        public ClassType ClassType { get; set; }
        public string Code { get; set; }
        public int AutoId { get; set; }
    
        public virtual ICollection<Department> DepartmentChildren { get; set; }
        public virtual Department DepartmentParent { get; set; }
        public virtual ICollection<DepartmentUser> DepartmentUser { get; set; }
        public virtual ICollection<DepartmentUser> TopDepartmentUser { get; set; }
        public virtual ICollection<Learned> Learned { get; set; }
        public virtual ICollection<Taught> Taught { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual Department DepartmentRoot { get; set; }
    }
}
