//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    
    public enum DepartmentUserType : int
    {
        部门主职教师 = -1,
        部门兼职教师 = -2,
        班级学生 = 1,
        班级班主任 = 2,
        借调前部门主职教师 = -3,
        借调后部门主职教师 = -4,
        教师可查看部门 = -5,
        年级行政领导 = 3
    }
}
