//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class Group
    {
        public Group()
        {
            this.GroupUser = new HashSet<GroupUser>();
            this.GroupBoard = new HashSet<GroupBoard>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Serial { get; set; }
        public GroupType Type { get; set; }
        public string Icon { get; set; }
        public OpenType OpenType { get; set; }
        public State State { get; set; }
        public int Ordinal { get; set; }
        public string Introduction { get; set; }
        public Nullable<System.Guid> GradeId { get; set; }
        public Nullable<System.Guid> CourseId { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual Catalog Catalog1 { get; set; }
        public virtual ICollection<GroupUser> GroupUser { get; set; }
        public virtual ICollection<GroupBoard> GroupBoard { get; set; }
    }
}
