//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class GroupUser
    {
        public System.Guid GroupId { get; set; }
        public System.Guid UserId { get; set; }
        public GroupUserType Type { get; set; }
        public System.DateTime Time { get; set; }
        public State State { get; set; }
        public int Ordinal { get; set; }
    
        public virtual User User { get; set; }
        public virtual Group Group { get; set; }
    }
}
