//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class Log
    {
        public System.Guid Id { get; set; }
        public LogAction Action { get; set; }
        public string ActionContent { get; set; }
        public System.Guid ObjectA { get; set; }
        public System.Guid ObjectB { get; set; }
        public System.Guid ObjectC { get; set; }
        public bool NotifiedA { get; set; }
        public bool NotifiedB { get; set; }
        public bool NotifiedC { get; set; }
        public decimal Value { get; set; }
        public System.DateTime Time { get; set; }
        public State State { get; set; }
    }
}
