//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    
    public enum LogAction : int
    {
        用户收藏资源 = 1,
        用户评论资源 = 2,
        用户评定资源 = 3,
        用户浏览资源 = 4,
        用户下载资源 = 5,
        用户课堂评估 = 6,
        用户发布视频 = 7,
        用户发布文章 = 8,
        用户发布课件 = 9,
        用户发布试卷 = 10,
        用户关注用户 = 11,
        用户浏览用户 = 12,
        用户登录应用 = 13,
        用户创建团队 = 14,
        用户团队资源 = 15
    }
}
