//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class MediaNote
    {
        public System.Guid ResourceId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime Time { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public string A { get; set; }
        public string B { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual User User { get; set; }
    }
}
