//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class PrizeCredit
    {
        public ResourcePrizeRange PrizeRange { get; set; }
        public ResourcePrizeLevel PrizeLevel { get; set; }
        public int Credit { get; set; }
    }
}
