//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class ResourceAssess
    {
        public System.Guid ResourceId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid AssessTableId { get; set; }
        public string Content { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual AssessTable AssessTable { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual User User { get; set; }
    }
}
