//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    
    public enum ResourceFileType : int
    {
        Word = 1,
        Excel = 2,
        Powerpoint = 3,
        Pdf = 4,
        Zip = 5,
        Image = 6,
        Media = 7,
        None = 0
    }
}
