//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    
    public enum ResourceFileType : int
    {
        Word = 1,
        Excel = 2,
        Powerpoint = 3,
        Pdf = 4,
        Zip = 5,
        Image = 6,
        Media = 7
    }
}
