//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    
    public enum ResourceOperationType : int
    {
        Favourite = 1,
        Comment = 2,
        Rate = 3,
        Grade = 4,
        View = 5,
        Download = 6
    }
}
