//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    
    public enum ResourcePrizeLevel : int
    {
        特等奖 = 1,
        一等奖 = 2,
        二等奖 = 3,
        三等奖 = 4,
        其他 = 5
    }
}
