//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class ResourceLog
    {
        public System.Guid Id { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Article { get; set; }
        public int Courseware { get; set; }
        public int Paper { get; set; }
        public int Media { get; set; }
        public int View { get; set; }
        public int Favourite { get; set; }
        public int Download { get; set; }
        public int Comment { get; set; }
        public int Reply { get; set; }
        public int Rate { get; set; }
        public int Credit { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public System.Guid CampusId { get; set; }
    
        public virtual User User { get; set; }
    }
}
