//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    
    public enum ResourceLogType : int
    {
        发布视频 = 1,
        发布文章 = 2,
        发布课件 = 3,
        发布试卷 = 4,
        浏览资源 = 5,
        收藏资源 = 6,
        下载资源 = 7,
        评论资源 = 8,
        回复评论 = 9,
        评定资源 = 10,
        个人积分 = 11
    }
}
