//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class ResourceLog
    {
        public System.Guid Id { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Article { get; set; }
        public int Courseware { get; set; }
        public int Paper { get; set; }
        public int Media { get; set; }
        public int View { get; set; }
        public int Favourite { get; set; }
        public int Download { get; set; }
        public int Comment { get; set; }
        public int Reply { get; set; }
        public int Rate { get; set; }
        public int Credit { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public System.Guid CampusId { get; set; }
    
        public virtual User User { get; set; }
    }
}
