//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    
    public enum ResourcePrizeRange : int
    {
        全国 = 1,
        省级 = 2,
        市级 = 3,
        区级 = 4,
        校级 = 5,
        其他 = 6
    }
}
