//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    
    public enum ResourceOperationType : int
    {
        Favourite = 1,
        Comment = 2,
        Rate = 3,
        Grade = 4,
        View = 5,
        Download = 6
    }
}
