//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    
    public enum State : int
    {
        内置 = 0,
        启用 = 1,
        审核 = 2,
        默认 = 3,
        停用 = 4,
        删除 = 5,
        历史 = 9
    }
}
