//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class UserWeChat
    {
        public System.Guid 用户ID { get; set; }
        public string 用户单位 { get; set; }
        public string 用户姓名 { get; set; }
        public string 微信ID { get; set; }
        public bool 用户在编 { get; set; }
    }
}
