//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class UserFavourite
    {
        public System.Guid UserId { get; set; }
        public System.Guid FavouriteUserId { get; set; }
        public State State { get; set; }
    
        public virtual User User { get; set; }
        public virtual User FavouriteUser { get; set; }
    }
}
