//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class ViewRole
    {
        public System.Guid RoleId { get; set; }
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.Guid> DepartmentId { get; set; }
        public string RoleName { get; set; }
        public State State { get; set; }
    }
}
