//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class ViewTeacherExport
    {
        public string 账号 { get; set; }
        public string 姓名 { get; set; }
        public string 拼音 { get; set; }
        public string 状态 { get; set; }
        public string 校区 { get; set; }
        public string 部门 { get; set; }
        public string 主兼职 { get; set; }
        public string 手机号码 { get; set; }
        public string 电子邮件 { get; set; }
        public string 身份证号 { get; set; }
        public string 性别 { get; set; }
        public string 籍贯 { get; set; }
        public Nullable<System.DateTime> 出生日期 { get; set; }
        public string 现居住地 { get; set; }
        public string 民族 { get; set; }
    }
}
