//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class ViewResourceX
    {
        public System.Guid CatalogId { get; set; }
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public int Type { get; set; }
        public int OpenType { get; set; }
        public int FileType { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Content { get; set; }
        public bool Converted { get; set; }
        public string Thumbnail { get; set; }
        public string SourceName { get; set; }
        public string Source { get; set; }
        public string Preview { get; set; }
        public string Image { get; set; }
        public bool Prize { get; set; }
        public Nullable<int> PrizeRange { get; set; }
        public Nullable<int> PrizeLevel { get; set; }
        public int Credit { get; set; }
        public int State { get; set; }
        public int Favourite { get; set; }
        public int Comment { get; set; }
        public int Rate { get; set; }
        public decimal Grade { get; set; }
        public int View { get; set; }
        public int Download { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<System.Guid> GradeId { get; set; }
        public Nullable<System.Guid> CourseId { get; set; }
        public Nullable<System.Guid> CampusId { get; set; }
        public int AssistantType { get; set; }
    }
}
