//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class ViewQueryTaught
    {
        public System.Guid DepartmentId { get; set; }
        public System.Guid CourseId { get; set; }
        public int State { get; set; }
        public string 学校 { get; set; }
        public string 届 { get; set; }
        public string 班级 { get; set; }
        public string 课程名称 { get; set; }
        public string 教师 { get; set; }
    }
}
