//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class ViewQueryResource
    {
        public System.Guid Id { get; set; }
        public System.Guid CampusId { get; set; }
        public int 年份 { get; set; }
        public int 月份 { get; set; }
        public int 发布文章 { get; set; }
        public int 发布课件 { get; set; }
        public int 发布试卷 { get; set; }
        public int 发布视频 { get; set; }
        public int 浏览资源 { get; set; }
        public int 收藏资源 { get; set; }
        public int 下载资源 { get; set; }
        public int 评论资源 { get; set; }
        public int 回复评论 { get; set; }
        public int 评定资源 { get; set; }
        public int 获得积分 { get; set; }
        public string 学校 { get; set; }
        public string 教师 { get; set; }
    }
}
