//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class View_ResourceAssess
    {
        public string ResultContent { get; set; }
        public string DisplayName { get; set; }
        public string Content { get; set; }
        public System.Guid Id { get; set; }
        public System.Guid RId { get; set; }
    }
}
