//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class ViewQueryResource
    {
        public System.Guid Id { get; set; }
        public System.Guid CampusId { get; set; }
        public int 年份 { get; set; }
        public int 月份 { get; set; }
        public int 发布文章 { get; set; }
        public int 发布课件 { get; set; }
        public int 发布试卷 { get; set; }
        public int 发布视频 { get; set; }
        public int 浏览资源 { get; set; }
        public int 收藏资源 { get; set; }
        public int 下载资源 { get; set; }
        public int 评论资源 { get; set; }
        public int 回复评论 { get; set; }
        public int 评定资源 { get; set; }
        public int 获得积分 { get; set; }
        public string 学校 { get; set; }
        public string 教师 { get; set; }
    }
}
