//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class ViewQueryStudent
    {
        public string 姓名 { get; set; }
        public string 状态 { get; set; }
        public string 账号 { get; set; }
        public string 学校 { get; set; }
        public string 届 { get; set; }
        public string 班级 { get; set; }
        public int 学号 { get; set; }
        public string 学籍号 { get; set; }
        public string 身份证号 { get; set; }
        public string 性别 { get; set; }
        public string 籍贯 { get; set; }
        public Nullable<System.DateTime> 出生日期 { get; set; }
        public string 现居住地 { get; set; }
        public string 民族 { get; set; }
        public string 联系人 { get; set; }
        public string 联系号码 { get; set; }
        public string 拼音 { get; set; }
    }
}
