//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class ViewStatistics
    {
        public Nullable<int> Count { get; set; }
        public System.Guid CampusId { get; set; }
        public System.Guid GradeId { get; set; }
        public ResourceType Type { get; set; }
    }
}
