//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class View_ResourceAssess
    {
        public string ResultContent { get; set; }
        public string DisplayName { get; set; }
        public string Content { get; set; }
        public System.Guid Id { get; set; }
        public System.Guid RId { get; set; }
    }
}
