//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class ViewLearned
    {
        public System.Guid DepartmentId { get; set; }
        public System.Guid CourseId { get; set; }
        public string CourseName { get; set; }
        public int Ordinal { get; set; }
    }
}
