//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homory.Model
{
    using System;
    using System.Collections.Generic;
    
    [EntityFramework.Audit.Audit]
    public partial class 机构用户关系
    {
        public int Id { get; set; }
        public System.Guid Batch { get; set; }
        public string BatchType { get; set; }
        public System.Guid UserId { get; set; }
        public string UserSyncId { get; set; }
        public System.Guid OrgId { get; set; }
        public string OrgSyncId { get; set; }
        public System.DateTime Time { get; set; }
        public int State { get; set; }
    }
}
