//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Tool.Import.App_Code.ToModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_piccurr
    {
        public int id { get; set; }
        public string otype { get; set; }
        public Nullable<int> pid { get; set; }
        public string rid { get; set; }
        public Nullable<System.DateTime> bdate { get; set; }
        public Nullable<int> num { get; set; }
        public string opcode { get; set; }
        public Nullable<System.DateTime> opdate { get; set; }
        public string memo { get; set; }
        public string txm { get; set; }
    }
}
