//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Tool.Import.App_Code.ToModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class pcodelist
    {
        public string code { get; set; }
        public string name { get; set; }
        public int rank { get; set; }
        public int id { get; set; }
        public int parent { get; set; }
        public string type { get; set; }
    }
}
