//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows.MMS.Tool.Import.App_Code.ToModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_toolinfo
    {
        public int tid { get; set; }
        public string code { get; set; }
        public string classcode { get; set; }
        public string name { get; set; }
        public string createor { get; set; }
        public string gg { get; set; }
        public string xh { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> num1 { get; set; }
        public Nullable<double> price { get; set; }
        public string opcode { get; set; }
        public Nullable<System.DateTime> opdate { get; set; }
        public Nullable<int> syfw { get; set; }
        public string cfdd { get; set; }
        public string gzd { get; set; }
        public string state { get; set; }
        public Nullable<int> lb { get; set; }
    }
}
