//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class C____OnlineCountStatistics
{
    public int Key { get; set; }
    public string Id { get; set; }
    public int Online { get; set; }
    public System.DateTime Time { get; set; }
}

public partial class Department
{
    public string DeptID { get; set; }
    public string DeptName { get; set; }
    public string DeptParentID { get; set; }
    public Nullable<int> DeptSort { get; set; }
    public string DeptDesc { get; set; }
    public int DeptDelFlag { get; set; }
    public string DeptGuid { get; set; }
    public string DeptPy { get; set; }
    public string DeptPrincipal { get; set; }
    public string UpperLeader { get; set; }
    public Nullable<int> IsCompany { get; set; }
    public string UnitID { get; set; }
    public string BMID { get; set; }
}

public partial class RelationshipUsers
{
    public string RelaType { get; set; }
    public string UserID { get; set; }
    public string DeptID { get; set; }
    public string PosiID { get; set; }
    public int DeptLeader { get; set; }
    public int UserOrder { get; set; }
    public int RelaPrimary { get; set; }
    public Nullable<int> StatID { get; set; }
    public string ID { get; set; }
    public string DelFlag { get; set; }
}

public partial class Users
{
    public string UserID { get; set; }
    public string UserName { get; set; }
    public string PassWord { get; set; }
    public string EmployeeID { get; set; }
    public Nullable<int> PassWordType { get; set; }
    public Nullable<int> PassWordTerm { get; set; }
    public Nullable<int> PassWordLeastLengh { get; set; }
    public System.DateTime PWDLastUpdateTime { get; set; }
    public string PhotoURL { get; set; }
    public string Status { get; set; }
    public int LonginStatus { get; set; }
    public Nullable<System.DateTime> LastLonginActive { get; set; }
    public int SysFlag { get; set; }
    public int UserType { get; set; }
    public Nullable<System.DateTime> LastFlushTime { get; set; }
    public string SessionID { get; set; }
    public string LoginCode { get; set; }
    public string LoginIp { get; set; }
    public System.DateTime RegTime { get; set; }
    public int Reg_AipPower { get; set; }
    public string UserPy { get; set; }
    public string LastLonginIP { get; set; }
    public Nullable<int> WorkStatus { get; set; }
    public int InPhase { get; set; }
    public string UnitID { get; set; }
    public string YHID { get; set; }
}
