//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.JHMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageApprove
    {
        public int MessageID { get; set; }
        public Nullable<int> ModuleTypeID { get; set; }
        public string ModuleTypeName { get; set; }
        public string MessageTitle { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string SendUserCode { get; set; }
        public string MessageHTML { get; set; }
        public string MessageFileName { get; set; }
        public string FileType { get; set; }
        public string KeyWord { get; set; }
        public Nullable<int> IsPhoto { get; set; }
        public Nullable<int> PhotoId { get; set; }
        public string MessageArea { get; set; }
        public string MessageType { get; set; }
        public Nullable<int> IsScroll { get; set; }
        public Nullable<int> ScrollDay { get; set; }
        public Nullable<int> Instancy { get; set; }
        public string Attendment { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> ApproveFLag { get; set; }
        public string Field01 { get; set; }
        public string Field02 { get; set; }
        public string Field03 { get; set; }
        public string Field04 { get; set; }
        public string Field05 { get; set; }
        public string Field06 { get; set; }
        public string Field07 { get; set; }
        public string Field08 { get; set; }
        public string Field09 { get; set; }
        public string Field10 { get; set; }
        public string Field11 { get; set; }
        public string Field12 { get; set; }
        public string Field13 { get; set; }
        public string Field14 { get; set; }
        public string Field15 { get; set; }
        public string Field16 { get; set; }
        public string Field17 { get; set; }
        public string Field18 { get; set; }
        public string Field19 { get; set; }
        public string Field20 { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public Nullable<int> PublishOut { get; set; }
        public Nullable<int> ImportGrade { get; set; }
        public string PublishDept { get; set; }
        public Nullable<System.DateTime> ApproveTime { get; set; }
        public string ApproveMan { get; set; }
        public Nullable<int> Anonymity { get; set; }
        public string selquarters { get; set; }
        public string seldept { get; set; }
        public Nullable<int> IsCopy { get; set; }
    }
}
