//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.JHMobile.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class C6Entities : DbContext
    {
        public C6Entities()
            : base("name=C6Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<f____Mobile_Count_Result> f____Mobile_Count(string loginCode)
        {
            var loginCodeParameter = loginCode != null ?
                new ObjectParameter("LoginCode", loginCode) :
                new ObjectParameter("LoginCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f____Mobile_Count_Result>("f____Mobile_Count", loginCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> f____Mobile_Count_CallToRead(string loginCode)
        {
            var loginCodeParameter = loginCode != null ?
                new ObjectParameter("LoginCode", loginCode) :
                new ObjectParameter("LoginCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("f____Mobile_Count_CallToRead", loginCodeParameter);
        }
    
        public virtual ObjectResult<f____Mobile_List_CallToRead_Result> f____Mobile_List_CallToRead(string loginCode)
        {
            var loginCodeParameter = loginCode != null ?
                new ObjectParameter("LoginCode", loginCode) :
                new ObjectParameter("LoginCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f____Mobile_List_CallToRead_Result>("f____Mobile_List_CallToRead", loginCodeParameter);
        }
    
        public virtual ObjectResult<f____Mobile_List_CallAttachment_Result> f____Mobile_List_CallAttachment(string callID)
        {
            var callIDParameter = callID != null ?
                new ObjectParameter("CallID", callID) :
                new ObjectParameter("CallID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f____Mobile_List_CallAttachment_Result>("f____Mobile_List_CallAttachment", callIDParameter);
        }
    
        public virtual int f____Mobile_Do_CallRead(Nullable<int> callNoSeeId)
        {
            var callNoSeeIdParameter = callNoSeeId.HasValue ?
                new ObjectParameter("CallNoSeeId", callNoSeeId) :
                new ObjectParameter("CallNoSeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f____Mobile_Do_CallRead", callNoSeeIdParameter);
        }
    
        public virtual ObjectResult<f____Mobile_List_CallRead_Result> f____Mobile_List_CallRead(string loginCode)
        {
            var loginCodeParameter = loginCode != null ?
                new ObjectParameter("LoginCode", loginCode) :
                new ObjectParameter("LoginCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f____Mobile_List_CallRead_Result>("f____Mobile_List_CallRead", loginCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> f____Mobile_Count_CallRead(string loginCode)
        {
            var loginCodeParameter = loginCode != null ?
                new ObjectParameter("LoginCode", loginCode) :
                new ObjectParameter("LoginCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("f____Mobile_Count_CallRead", loginCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> f____Mobile_Count_MessageModule(string loginCode, string moduleType)
        {
            var loginCodeParameter = loginCode != null ?
                new ObjectParameter("LoginCode", loginCode) :
                new ObjectParameter("LoginCode", typeof(string));
    
            var moduleTypeParameter = moduleType != null ?
                new ObjectParameter("ModuleType", moduleType) :
                new ObjectParameter("ModuleType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("f____Mobile_Count_MessageModule", loginCodeParameter, moduleTypeParameter);
        }
    
        public virtual ObjectResult<f____Mobile_List_MessageModule_Result> f____Mobile_List_MessageModule(string loginCode, string moduleType)
        {
            var loginCodeParameter = loginCode != null ?
                new ObjectParameter("LoginCode", loginCode) :
                new ObjectParameter("LoginCode", typeof(string));
    
            var moduleTypeParameter = moduleType != null ?
                new ObjectParameter("ModuleType", moduleType) :
                new ObjectParameter("ModuleType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f____Mobile_List_MessageModule_Result>("f____Mobile_List_MessageModule", loginCodeParameter, moduleTypeParameter);
        }
    
        public virtual ObjectResult<f____Mobile_List_MessageModuleSingle_Result> f____Mobile_List_MessageModuleSingle(Nullable<int> messageId)
        {
            var messageIdParameter = messageId.HasValue ?
                new ObjectParameter("MessageId", messageId) :
                new ObjectParameter("MessageId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f____Mobile_List_MessageModuleSingle_Result>("f____Mobile_List_MessageModuleSingle", messageIdParameter);
        }
    
        public virtual ObjectResult<string> f____Mobile_List_MessageModuleSingleRead(Nullable<int> messageId, string moduleType)
        {
            var messageIdParameter = messageId.HasValue ?
                new ObjectParameter("MessageId", messageId) :
                new ObjectParameter("MessageId", typeof(int));
    
            var moduleTypeParameter = moduleType != null ?
                new ObjectParameter("ModuleType", moduleType) :
                new ObjectParameter("ModuleType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f____Mobile_List_MessageModuleSingleRead", messageIdParameter, moduleTypeParameter);
        }
    
        public virtual ObjectResult<f____Mobile_List_MessageAttachment_Result> f____Mobile_List_MessageAttachment(string messageID)
        {
            var messageIDParameter = messageID != null ?
                new ObjectParameter("MessageID", messageID) :
                new ObjectParameter("MessageID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f____Mobile_List_MessageAttachment_Result>("f____Mobile_List_MessageAttachment", messageIDParameter);
        }
    
        public virtual int f____Mobile_Do_MessageRead(Nullable<int> messageId, string moduleType, string loginCode)
        {
            var messageIdParameter = messageId.HasValue ?
                new ObjectParameter("MessageId", messageId) :
                new ObjectParameter("MessageId", typeof(int));
    
            var moduleTypeParameter = moduleType != null ?
                new ObjectParameter("ModuleType", moduleType) :
                new ObjectParameter("ModuleType", typeof(string));
    
            var loginCodeParameter = loginCode != null ?
                new ObjectParameter("LoginCode", loginCode) :
                new ObjectParameter("LoginCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f____Mobile_Do_MessageRead", messageIdParameter, moduleTypeParameter, loginCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> f____Mobile_List_MessageModuleSingleReadPersonal(Nullable<int> messageId, string moduleType, string loginCode)
        {
            var messageIdParameter = messageId.HasValue ?
                new ObjectParameter("MessageId", messageId) :
                new ObjectParameter("MessageId", typeof(int));
    
            var moduleTypeParameter = moduleType != null ?
                new ObjectParameter("ModuleType", moduleType) :
                new ObjectParameter("ModuleType", typeof(string));
    
            var loginCodeParameter = loginCode != null ?
                new ObjectParameter("LoginCode", loginCode) :
                new ObjectParameter("LoginCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("f____Mobile_List_MessageModuleSingleReadPersonal", messageIdParameter, moduleTypeParameter, loginCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> f____Mobile_Count_Message(string loginCode)
        {
            var loginCodeParameter = loginCode != null ?
                new ObjectParameter("LoginCode", loginCode) :
                new ObjectParameter("LoginCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("f____Mobile_Count_Message", loginCodeParameter);
        }
    
        public virtual ObjectResult<f____Mobile_List_Message_Result> f____Mobile_List_Message(string loginCode)
        {
            var loginCodeParameter = loginCode != null ?
                new ObjectParameter("LoginCode", loginCode) :
                new ObjectParameter("LoginCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f____Mobile_List_Message_Result>("f____Mobile_List_Message", loginCodeParameter);
        }
    
        public virtual ObjectResult<string> f____Mobile_List_User(string loginCode)
        {
            var loginCodeParameter = loginCode != null ?
                new ObjectParameter("LoginCode", loginCode) :
                new ObjectParameter("LoginCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("f____Mobile_List_User", loginCodeParameter);
        }
    
        public virtual ObjectResult<f____Mobile_List_MessageType_Result> f____Mobile_List_MessageType(Nullable<int> appG_ID)
        {
            var appG_IDParameter = appG_ID.HasValue ?
                new ObjectParameter("AppG_ID", appG_ID) :
                new ObjectParameter("AppG_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f____Mobile_List_MessageType_Result>("f____Mobile_List_MessageType", appG_IDParameter);
        }
    }
}
