//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Housing_Department
{
    public System.Guid Id { get; set; }
    public string Name { get; set; }
    public int Ordinal { get; set; }
}

public partial class Housing_Member
{
    public System.Guid DepartmentId { get; set; }
    public System.Guid UserId { get; set; }
    public System.Guid OnlineId { get; set; }
}

public partial class User
{
    public System.Guid Id { get; set; }
    public string Account { get; set; }
    public string RealName { get; set; }
    public string DisplayName { get; set; }
    public string Icon { get; set; }
    public System.Guid Stamp { get; set; }
    public string Password { get; set; }
    public string PasswordEx { get; set; }
    public string CryptoKey { get; set; }
    public string CryptoSalt { get; set; }
    public int Type { get; set; }
    public int State { get; set; }
    public int Ordinal { get; set; }
    public string Description { get; set; }
    public string PinYin { get; set; }
    public string WXOpenId { get; set; }
}
